- hosts: localhost
  become: yes
  vars_prompt:
    - name: username
      prompt: Enter Docker Login Username
    - name: password
      prompt: Enter Docker Login Password
  tasks:
    - name: Install Docker Engine
      apt:
        name: docker.io
        state: present
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true
    - name: Log into DockerHub
      community.docker.docker_login:
        username: "{{ username }}"
        password: "{{ password }}"
    - name: Pull nginx Docker image
      docker_image:
        name: nginx
        source: pull
    - name: Run nginx Docker container
      docker_container:
        name: nginx-example-docker
        image: nginx
        state: started
        ports:
          - "443:80"
